"""
Database seed script - populates the database with 400+ products for testing.
Run: cd backend && set PYTHONPATH=. && python app/seed.py
"""
import asyncio, random
from app.core.database import AsyncSessionLocal, init_db
from app.models.product import Category, Brand, Product
from app.models.user import User
from app.core.security import get_password_hash


def _img(keyword: str, idx: int = 1, w: int = 640, h: int = 480) -> str:
    """Generate a product image URL from picsum or via DummyImage."""
    seed = f"{keyword}-{idx}"
    return f"https://picsum.photos/seed/{seed}/{w}/{h}"


def _make(name, cat, brand, price, orig=None, disc=0.0, stock=100,
          tags=None, feat=False, sale=False, prem=False, new_arr=False,
          rating=None, reviews=None, desc=None, img_kw=None):
    slug = name.lower().replace(" ", "-").replace("'", "").replace("&", "and")
    slug = slug.replace("(", "").replace(")", "").replace(",", "")
    kw = img_kw or slug
    r = rating or round(random.uniform(3.8, 4.9), 1)
    rev = reviews or random.randint(50, 15000)
    return Product(
        name=name, slug=slug,
        description=desc or f"High quality {name}. Best in class performance and design.",
        short_description=f"Premium {name}" if prem else name,
        price=price, original_price=orig or price,
        discount_percentage=disc, category_id=cat, brand_id=brand,
        stock_quantity=stock,
        images=[_img(kw, 1), _img(kw, 2), _img(kw, 3)],
        tags=tags or [], avg_rating=r, review_count=rev,
        is_featured=feat, is_on_sale=sale, is_premium=prem,
        is_new_arrival=new_arr,
    )


async def seed():
    await init_db()
    async with AsyncSessionLocal() as db:
        # ===== CATEGORIES (8) =====
        cats = [
            Category(name="Electronics", slug="electronics",
                     description="Smartphones, Laptops, Tablets, Audio, Cameras & Accessories",
                     image_url=_img("electronics-cat", 0, 800, 400), display_order=1),
            Category(name="Fashion", slug="fashion",
                     description="Clothing, Shoes, Bags, Watches & Accessories for Men & Women",
                     image_url=_img("fashion-cat", 0, 800, 400), display_order=2),
            Category(name="Home & Kitchen", slug="home-kitchen",
                     description="Furniture, Appliances, Cookware, Decor & Home Essentials",
                     image_url=_img("home-kitchen-cat", 0, 800, 400), display_order=3),
            Category(name="Books", slug="books",
                     description="Fiction, Non-fiction, Academic, Self-help & Comics",
                     image_url=_img("books-cat", 0, 800, 400), display_order=4),
            Category(name="Sports & Fitness", slug="sports-fitness",
                     description="Gym Equipment, Sportswear, Shoes, Supplements & Outdoor Gear",
                     image_url=_img("sports-cat", 0, 800, 400), display_order=5),
            Category(name="Beauty & Personal Care", slug="beauty-personal-care",
                     description="Skincare, Makeup, Haircare, Fragrance & Grooming",
                     image_url=_img("beauty-cat", 0, 800, 400), display_order=6),
            Category(name="Toys & Games", slug="toys-games",
                     description="Kids Toys, Board Games, Puzzles, Action Figures & Outdoor Play",
                     image_url=_img("toys-cat", 0, 800, 400), display_order=7),
            Category(name="Groceries", slug="groceries",
                     description="Food, Beverages, Snacks, Household & Daily Essentials",
                     image_url=_img("groceries-cat", 0, 800, 400), display_order=8),
        ]
        db.add_all(cats)
        await db.flush()

        # ===== BRANDS (15) =====
        brands = [
            Brand(name="Apple", slug="apple", is_premium=True,
                  logo_url="https://img.icons8.com/ios-filled/100/mac-os.png"),
            Brand(name="Samsung", slug="samsung", is_premium=False,
                  logo_url="https://img.icons8.com/color/100/samsung.png"),
            Brand(name="Nike", slug="nike", is_premium=True,
                  logo_url="https://img.icons8.com/ios-filled/100/nike.png"),
            Brand(name="Adidas", slug="adidas", is_premium=False,
                  logo_url="https://img.icons8.com/ios-filled/100/adidas-trefoil.png"),
            Brand(name="Sony", slug="sony", is_premium=True,
                  logo_url="https://img.icons8.com/ios-filled/100/sony.png"),
            Brand(name="LG", slug="lg", is_premium=False,
                  logo_url="https://img.icons8.com/ios-filled/100/lg.png"),
            Brand(name="Puma", slug="puma", is_premium=False,
                  logo_url="https://img.icons8.com/ios-filled/100/puma.png"),
            Brand(name="Boat", slug="boat", is_premium=False,
                  logo_url=_img("boat-brand", 0, 100, 100)),
            Brand(name="OnePlus", slug="oneplus", is_premium=False,
                  logo_url=_img("oneplus-brand", 0, 100, 100)),
            Brand(name="Gucci", slug="gucci", is_premium=True,
                  logo_url=_img("gucci-brand", 0, 100, 100)),
            Brand(name="HP", slug="hp", is_premium=False,
                  logo_url="https://img.icons8.com/ios-filled/100/hp.png"),
            Brand(name="Dell", slug="dell", is_premium=False,
                  logo_url="https://img.icons8.com/ios-filled/100/dell.png"),
            Brand(name="Levi's", slug="levis", is_premium=False,
                  logo_url=_img("levis-brand", 0, 100, 100)),
            Brand(name="Lakme", slug="lakme", is_premium=False,
                  logo_url=_img("lakme-brand", 0, 100, 100)),
            Brand(name="Nestle", slug="nestle", is_premium=False,
                  logo_url=_img("nestle-brand", 0, 100, 100)),
        ]
        db.add_all(brands)
        await db.flush()

        # ===== 400+ PRODUCTS (50+ per category) =====
        products = []

        # ---------- ELECTRONICS (cat=1) 55 products ----------
        elec = [
            _make("iPhone 15 Pro Max", 1, 1, 134900, 139900, 3.6, tags=["phone","premium","apple"], prem=True, feat=True, img_kw="iphone"),
            _make("iPhone 14", 1, 1, 59900, 79900, 25.0, tags=["phone","apple"], sale=True, img_kw="iphone14"),
            _make("MacBook Pro M3 14-inch", 1, 1, 199900, tags=["laptop","premium"], prem=True, img_kw="macbook"),
            _make("MacBook Air M2", 1, 1, 99900, 114900, 13.1, tags=["laptop","apple"], sale=True, img_kw="macbook-air"),
            _make("iPad Pro 12.9", 1, 1, 112900, tags=["tablet","premium"], prem=True, img_kw="ipad-pro"),
            _make("iPad Air M1", 1, 1, 59900, 69900, 14.3, tags=["tablet","apple"], sale=True, img_kw="ipad-air"),
            _make("Apple Watch Ultra 2", 1, 1, 89900, tags=["watch","premium"], prem=True, new_arr=True, img_kw="apple-watch"),
            _make("Apple Watch SE", 1, 1, 29900, 34900, 14.3, tags=["watch","apple"], sale=True, img_kw="apple-watch-se"),
            _make("AirPods Pro 2", 1, 1, 24900, tags=["earbuds","premium"], prem=True, img_kw="airpods"),
            _make("AirPods 3rd Gen", 1, 1, 19900, 22900, 13.1, tags=["earbuds","apple"], sale=True, img_kw="airpods3"),
            _make("Samsung Galaxy S24 Ultra", 1, 2, 129999, 134999, 3.7, tags=["phone","premium"], prem=True, feat=True, img_kw="galaxy-s24"),
            _make("Samsung Galaxy S24", 1, 2, 74999, 79999, 6.3, tags=["phone","samsung"], img_kw="galaxy-s24-base"),
            _make("Samsung Galaxy A55", 1, 2, 24999, 29999, 16.7, tags=["phone","mid-range"], sale=True, img_kw="galaxy-a55"),
            _make("Samsung Galaxy A15", 1, 2, 13999, 16999, 17.6, tags=["phone","budget"], sale=True, img_kw="galaxy-a15"),
            _make("Samsung Galaxy Tab S9", 1, 2, 74999, tags=["tablet","samsung"], img_kw="galaxy-tab"),
            _make("Samsung Galaxy Buds FE", 1, 2, 6999, 9999, 30.0, tags=["earbuds","wireless"], sale=True, new_arr=True, img_kw="galaxy-buds"),
            _make("Samsung Galaxy Watch 6", 1, 2, 26999, 32999, 18.2, tags=["watch","samsung"], sale=True, img_kw="galaxy-watch"),
            _make("Sony WH-1000XM5 Headphones", 1, 5, 29990, 34990, 14.3, tags=["headphones","premium","noise-cancelling"], prem=True, sale=True, img_kw="sony-xm5"),
            _make("Sony WF-1000XM5 Earbuds", 1, 5, 24990, 27990, 10.7, tags=["earbuds","premium"], prem=True, img_kw="sony-wf-xm5"),
            _make("Sony PS5 DualSense Controller", 1, 5, 5990, tags=["gaming","controller"], img_kw="ps5-controller"),
            _make("Sony PlayStation 5", 1, 5, 49990, tags=["gaming","console"], feat=True, img_kw="ps5"),
            _make("Sony Bravia 55 inch 4K TV", 1, 5, 69990, 89990, 22.2, tags=["tv","premium"], prem=True, sale=True, img_kw="sony-tv"),
            _make("Sony Alpha A7 IV Camera", 1, 5, 199990, tags=["camera","premium"], prem=True, img_kw="sony-camera"),
            _make("LG 55 inch OLED C3 TV", 1, 6, 129990, 149990, 13.3, tags=["tv","premium","oled"], prem=True, sale=True, img_kw="lg-oled"),
            _make("LG 43 inch 4K Smart TV", 1, 6, 32990, 39990, 17.5, tags=["tv","smart"], sale=True, img_kw="lg-tv-43"),
            _make("LG Gram 16 Laptop", 1, 6, 109990, tags=["laptop","ultrabook"], img_kw="lg-gram"),
            _make("LG Tone Free Earbuds", 1, 6, 9990, 14990, 33.4, tags=["earbuds","wireless"], sale=True, img_kw="lg-earbuds"),
            _make("Boat Rockerz 450 Headphones", 1, 8, 1499, 2990, 49.9, tags=["headphones","budget"], sale=True, img_kw="boat-headphones"),
            _make("Boat Airdopes 141 Earbuds", 1, 8, 999, 2490, 59.9, tags=["earbuds","budget"], sale=True, img_kw="boat-airdopes"),
            _make("Boat Stone 352 Speaker", 1, 8, 1299, 2490, 47.8, tags=["speaker","budget"], sale=True, img_kw="boat-speaker"),
            _make("Boat Smartwatch Storm", 1, 8, 1999, 4990, 59.9, tags=["watch","budget"], sale=True, img_kw="boat-watch"),
            _make("OnePlus 12", 1, 9, 64999, 69999, 7.1, tags=["phone","flagship"], feat=True, img_kw="oneplus-12"),
            _make("OnePlus Nord CE 3 Lite", 1, 9, 19999, 24999, 20.0, tags=["phone","mid-range"], sale=True, img_kw="oneplus-nord"),
            _make("OnePlus Buds Pro 2", 1, 9, 11999, 14999, 20.0, tags=["earbuds","wireless"], sale=True, img_kw="oneplus-buds"),
            _make("OnePlus Pad", 1, 9, 37999, 44999, 15.6, tags=["tablet","oneplus"], sale=True, img_kw="oneplus-pad"),
            _make("HP Pavilion 15 Laptop", 1, 11, 54990, 64990, 15.4, tags=["laptop","hp"], sale=True, img_kw="hp-pavilion"),
            _make("HP Spectre x360", 1, 11, 139990, tags=["laptop","premium"], prem=True, img_kw="hp-spectre"),
            _make("HP Wireless Mouse", 1, 11, 599, 1299, 53.9, tags=["mouse","accessory"], sale=True, img_kw="hp-mouse"),
            _make("HP LaserJet Printer", 1, 11, 14999, 19999, 25.0, tags=["printer","office"], sale=True, img_kw="hp-printer"),
            _make("Dell XPS 15 Laptop", 1, 12, 149990, tags=["laptop","premium"], prem=True, img_kw="dell-xps"),
            _make("Dell Inspiron 14 Laptop", 1, 12, 45990, 54990, 16.4, tags=["laptop","dell"], sale=True, img_kw="dell-inspiron"),
            _make("Dell 27 inch 4K Monitor", 1, 12, 29990, 37990, 21.1, tags=["monitor","dell"], sale=True, img_kw="dell-monitor"),
            _make("Dell Wireless Keyboard Combo", 1, 12, 1999, 3499, 42.9, tags=["keyboard","accessory"], sale=True, img_kw="dell-keyboard"),
            _make("JBL Flip 6 Speaker", 1, 8, 9999, 12999, 23.1, tags=["speaker","portable"], sale=True, img_kw="jbl-speaker"),
            _make("Logitech MX Master 3S Mouse", 1, 11, 8995, tags=["mouse","premium"], img_kw="logitech-mouse"),
            _make("GoPro Hero 12 Black", 1, 5, 44990, tags=["camera","action"], feat=True, img_kw="gopro"),
            _make("DJI Mini 3 Pro Drone", 1, 5, 79990, tags=["drone","premium"], prem=True, img_kw="dji-drone"),
            _make("Kindle Paperwhite 11th Gen", 1, 1, 14999, tags=["ereader","kindle"], img_kw="kindle"),
            _make("Chromecast with Google TV", 1, 6, 4999, 6999, 28.6, tags=["streaming","smart-home"], sale=True, img_kw="chromecast"),
            _make("Raspberry Pi 5", 1, 11, 5999, tags=["computer","diy"], new_arr=True, img_kw="raspberry-pi"),
            _make("USB-C Hub 7 in 1", 1, 12, 1499, 2999, 50.0, tags=["accessory","hub"], sale=True, img_kw="usb-hub"),
            _make("Power Bank 20000mAh", 1, 9, 1299, 2499, 48.0, tags=["accessory","charging"], sale=True, img_kw="power-bank"),
            _make("Wireless Charging Pad", 1, 2, 1999, 3499, 42.9, tags=["accessory","wireless"], sale=True, img_kw="wireless-charger"),
            _make("Smart LED Strip Lights 10m", 1, 6, 999, 1999, 50.0, tags=["smart-home","lighting"], sale=True, img_kw="led-strip"),
            _make("Ring Video Doorbell", 1, 1, 12990, tags=["smart-home","security"], img_kw="ring-doorbell"),
        ]
        products.extend(elec)

        # ---------- FASHION (cat=2) 55 products ----------
        fash = [
            _make("Gucci GG Marmont Shoulder Bag", 2, 10, 125000, tags=["bag","luxury"], prem=True, img_kw="gucci-bag"),
            _make("Gucci Ace Sneakers", 2, 10, 58000, tags=["shoes","luxury"], prem=True, img_kw="gucci-sneakers"),
            _make("Gucci Logo T-Shirt", 2, 10, 42000, tags=["clothing","luxury"], prem=True, img_kw="gucci-tshirt"),
            _make("Gucci Sunglasses", 2, 10, 28000, tags=["accessories","luxury"], prem=True, img_kw="gucci-sunglasses"),
            _make("Nike Air Jordan 1 Retro High", 2, 3, 16995, tags=["shoes","sneakers"], feat=True, prem=True, img_kw="jordan-1"),
            _make("Nike Air Max 270", 2, 3, 12995, 14995, 13.3, tags=["shoes","running"], sale=True, img_kw="airmax-270"),
            _make("Nike Dri-FIT T-Shirt", 2, 3, 1995, 2995, 33.4, tags=["clothing","sports"], sale=True, img_kw="nike-tshirt"),
            _make("Nike Dri-FIT Shorts", 2, 3, 1495, 2495, 40.1, tags=["clothing","sports"], sale=True, img_kw="nike-shorts"),
            _make("Nike Blazer Mid 77", 2, 3, 8695, tags=["shoes","casual"], img_kw="nike-blazer"),
            _make("Nike ACG Jacket Windbreaker", 2, 3, 7995, tags=["clothing","outdoor"], img_kw="nike-jacket"),
            _make("Nike Pro Leggings Women", 2, 3, 2795, 3995, 30.0, tags=["clothing","women","workout"], sale=True, img_kw="nike-leggings"),
            _make("Adidas Ultraboost 23 Running", 2, 4, 14999, 17999, 16.7, tags=["shoes","running"], sale=True, img_kw="adidas-ultraboost"),
            _make("Adidas Essentials T-Shirt", 2, 4, 999, 1999, 50.0, tags=["clothing","casual"], sale=True, img_kw="adidas-tshirt"),
            _make("Adidas Stan Smith Sneakers", 2, 4, 7999, tags=["shoes","classic"], img_kw="stan-smith"),
            _make("Adidas Track Pants", 2, 4, 2499, 3999, 37.5, tags=["clothing","casual"], sale=True, img_kw="adidas-pants"),
            _make("Adidas Backpack 30L", 2, 4, 2999, 4499, 33.3, tags=["bag","sports"], sale=True, img_kw="adidas-bag"),
            _make("Adidas NMD R1 V3", 2, 4, 12999, tags=["shoes","lifestyle"], img_kw="adidas-nmd"),
            _make("Puma RS-X Sneakers", 2, 7, 7999, 9999, 20.0, tags=["shoes","lifestyle"], sale=True, img_kw="puma-rsx"),
            _make("Puma Running Shoes Velocity", 2, 7, 2499, 4999, 50.0, tags=["shoes","running"], sale=True, img_kw="puma-running"),
            _make("Puma Polo T-Shirt", 2, 7, 1499, 2499, 40.0, tags=["clothing","casual"], sale=True, img_kw="puma-polo"),
            _make("Puma Track Jacket", 2, 7, 2999, 4999, 40.0, tags=["clothing","sports"], sale=True, img_kw="puma-jacket"),
            _make("Puma Backpack 25L", 2, 7, 1299, 2199, 40.9, tags=["bag","casual"], sale=True, img_kw="puma-backpack"),
            _make("Levi's 511 Slim Fit Jeans", 2, 13, 2799, 3999, 30.0, tags=["jeans","classic"], sale=True, img_kw="levis-511"),
            _make("Levi's 501 Original Jeans", 2, 13, 3499, 4999, 30.0, tags=["jeans","classic"], sale=True, img_kw="levis-501"),
            _make("Levi's Denim Jacket Trucker", 2, 13, 4999, 6999, 28.6, tags=["jacket","denim"], sale=True, img_kw="levis-jacket"),
            _make("Levi's Graphic T-Shirt", 2, 13, 999, 1799, 44.5, tags=["clothing","casual"], sale=True, img_kw="levis-tshirt"),
            _make("Levi's Chino Shorts", 2, 13, 1799, 2999, 40.0, tags=["shorts","casual"], sale=True, img_kw="levis-shorts"),
            _make("Men's Formal Blazer Black", 2, 13, 4999, tags=["formal","men"], img_kw="blazer-black"),
            _make("Women's Summer Floral Dress", 2, 7, 1999, 3499, 42.9, tags=["dress","women","summer"], sale=True, img_kw="floral-dress"),
            _make("Women's Handbag Leather Brown", 2, 10, 5999, tags=["bag","women","leather"], img_kw="leather-handbag"),
            _make("Men's Leather Belt Premium", 2, 13, 999, 1999, 50.0, tags=["belt","men","leather"], sale=True, img_kw="leather-belt"),
            _make("Unisex Aviator Sunglasses", 2, 7, 1499, 2999, 50.0, tags=["sunglasses","unisex"], sale=True, img_kw="aviator-sunglasses"),
            _make("Analog Watch Gold Men", 2, 5, 8999, tags=["watch","premium","men"], prem=True, img_kw="gold-watch"),
            _make("Digital Sports Watch", 2, 8, 1999, 3999, 50.0, tags=["watch","sports"], sale=True, img_kw="sports-watch"),
            _make("Cotton Polo Combo Pack of 3", 2, 4, 1499, 2999, 50.0, tags=["clothing","combo"], sale=True, img_kw="polo-combo"),
            _make("Women's Running Shoes Pink", 2, 3, 4995, 6995, 28.6, tags=["shoes","women","running"], sale=True, img_kw="women-running-shoes"),
            _make("Men's Casual Loafers", 2, 7, 2499, 3999, 37.5, tags=["shoes","casual","men"], sale=True, img_kw="mens-loafers"),
            _make("Women's Block Heels Sandals", 2, 10, 3499, tags=["shoes","women","heels"], img_kw="block-heels"),
            _make("Canvas Tote Bag", 2, 4, 799, 1499, 46.7, tags=["bag","casual"], sale=True, img_kw="tote-bag"),
            _make("Winter Woolen Scarf", 2, 13, 599, 1299, 53.9, tags=["scarf","winter"], sale=True, img_kw="woolen-scarf"),
            _make("Men's Swim Shorts", 2, 7, 999, 1999, 50.0, tags=["shorts","beachwear"], sale=True, img_kw="swim-shorts"),
            _make("Printed Hoodie Unisex", 2, 4, 1999, 3499, 42.9, tags=["hoodie","casual"], sale=True, img_kw="printed-hoodie"),
            _make("Slim Fit Chinos Beige", 2, 13, 1799, 2999, 40.0, tags=["pants","casual"], sale=True, img_kw="beige-chinos"),
            _make("Sports Bra High Impact", 2, 3, 1795, 2995, 40.1, tags=["women","workout"], sale=True, img_kw="sports-bra"),
            _make("Oversized Graphic Sweatshirt", 2, 4, 2499, 3999, 37.5, tags=["sweatshirt","streetwear"], sale=True, img_kw="graphic-sweatshirt"),
            _make("Kids Sneakers Light-Up", 2, 7, 1299, 2499, 48.0, tags=["shoes","kids"], sale=True, new_arr=True, img_kw="kids-sneakers"),
            _make("Silk Saree Traditional", 2, 10, 8999, tags=["saree","ethnic","women"], feat=True, img_kw="silk-saree"),
            _make("Cotton Kurta Set Men", 2, 13, 1499, 2999, 50.0, tags=["ethnic","men"], sale=True, img_kw="kurta-set"),
            _make("Laptop Messenger Bag", 2, 4, 2999, 4999, 40.0, tags=["bag","office"], sale=True, img_kw="messenger-bag"),
            _make("Faux Leather Wallet", 2, 13, 499, 999, 50.1, tags=["wallet","men"], sale=True, img_kw="leather-wallet"),
            _make("Denim Overalls Women", 2, 13, 2999, 4999, 40.0, tags=["overalls","women"], sale=True, new_arr=True, img_kw="denim-overalls"),
            _make("Cargo Pants Olive Green", 2, 7, 1999, 3499, 42.9, tags=["pants","casual"], sale=True, img_kw="cargo-pants"),
            _make("Embroidered Crop Top Women", 2, 10, 1299, 2499, 48.0, tags=["top","women","casual"], sale=True, img_kw="crop-top"),
            _make("Men's Bomber Jacket", 2, 4, 3999, 5999, 33.3, tags=["jacket","men","casual"], sale=True, img_kw="bomber-jacket"),
            _make("Yoga Pants High Waist Women", 2, 3, 2495, 3995, 37.5, tags=["pants","women","fitness"], sale=True, img_kw="yoga-pants"),
        ]
        products.extend(fash)

        # ---------- HOME & KITCHEN (cat=3) 50 products ----------
        home = [
            _make("Samsung 253L Refrigerator", 3, 2, 22990, 26990, 14.8, tags=["appliance","kitchen"], sale=True, img_kw="samsung-fridge"),
            _make("Samsung Front Load Washing Machine 7kg", 3, 2, 29990, 34990, 14.3, tags=["appliance","laundry"], sale=True, img_kw="samsung-washer"),
            _make("Samsung Microwave Oven 28L", 3, 2, 9990, 12990, 23.1, tags=["appliance","kitchen"], sale=True, img_kw="samsung-microwave"),
            _make("LG 260L Double Door Refrigerator", 3, 6, 28990, 33990, 14.7, tags=["appliance","kitchen"], sale=True, img_kw="lg-fridge"),
            _make("LG Top Load Washing Machine 8kg", 3, 6, 24990, 29990, 16.7, tags=["appliance","laundry"], sale=True, img_kw="lg-washer"),
            _make("LG Window AC 1.5 Ton 3 Star", 3, 6, 29990, 36990, 18.9, tags=["appliance","cooling"], sale=True, img_kw="lg-ac"),
            _make("Prestige Induction Cooktop", 3, 6, 2499, 3999, 37.5, tags=["kitchen","cooking"], sale=True, img_kw="induction-cooktop"),
            _make("Philips Air Fryer 4.1L", 3, 5, 7999, 9999, 20.0, tags=["kitchen","cooking"], sale=True, feat=True, img_kw="air-fryer"),
            _make("Instant Pot Duo 6 Quart", 3, 5, 8999, 12999, 30.8, tags=["kitchen","cooking"], sale=True, img_kw="instant-pot"),
            _make("Butterfly Mixer Grinder 750W", 3, 8, 2499, 3999, 37.5, tags=["kitchen","appliance"], sale=True, img_kw="mixer-grinder"),
            _make("Water Purifier RO+UV 7L", 3, 6, 9999, 14999, 33.3, tags=["kitchen","water"], sale=True, img_kw="water-purifier"),
            _make("Non-Stick Cookware Set 5 Pcs", 3, 8, 1999, 3999, 50.0, tags=["kitchen","cookware"], sale=True, img_kw="cookware-set"),
            _make("Stainless Steel Dinner Set 24 Pcs", 3, 8, 2999, 4999, 40.0, tags=["kitchen","dining"], sale=True, img_kw="dinner-set"),
            _make("Glass Water Bottle Set of 6", 3, 8, 799, 1499, 46.7, tags=["kitchen","bottles"], sale=True, img_kw="glass-bottles"),
            _make("Electric Kettle 1.5L Steel", 3, 5, 999, 1999, 50.0, tags=["kitchen","appliance"], sale=True, img_kw="electric-kettle"),
            _make("Wooden Dining Table 6 Seater", 3, 6, 24999, 34999, 28.6, tags=["furniture","dining"], sale=True, img_kw="dining-table"),
            _make("L-Shape Sofa Set Fabric", 3, 6, 34999, 49999, 30.0, tags=["furniture","living"], sale=True, feat=True, img_kw="sofa-set"),
            _make("Queen Size Bed with Storage", 3, 6, 19999, 29999, 33.3, tags=["furniture","bedroom"], sale=True, img_kw="queen-bed"),
            _make("Office Ergonomic Chair", 3, 11, 8999, 14999, 40.0, tags=["furniture","office"], sale=True, img_kw="office-chair"),
            _make("Bookshelf Wooden 5 Tier", 3, 6, 4999, 7999, 37.5, tags=["furniture","storage"], sale=True, img_kw="bookshelf"),
            _make("Wall Clock Modern Minimalist", 3, 8, 699, 1299, 46.2, tags=["decor","wall"], sale=True, img_kw="wall-clock"),
            _make("Table Lamp LED Study", 3, 5, 999, 1999, 50.0, tags=["lighting","study"], sale=True, img_kw="table-lamp"),
            _make("Floor Standing Mirror Full Length", 3, 6, 3999, 5999, 33.3, tags=["decor","mirror"], sale=True, img_kw="floor-mirror"),
            _make("Curtains Blackout 7ft Set of 2", 3, 8, 999, 1999, 50.0, tags=["decor","curtains"], sale=True, img_kw="blackout-curtains"),
            _make("Bedsheet King Size 100% Cotton", 3, 8, 799, 1499, 46.7, tags=["bedding","cotton"], sale=True, img_kw="bedsheet-cotton"),
            _make("Memory Foam Pillow Set of 2", 3, 8, 1299, 2499, 48.0, tags=["bedding","pillow"], sale=True, img_kw="memory-pillow"),
            _make("Vacuum Cleaner Robot Auto", 3, 2, 19999, 29999, 33.3, tags=["appliance","cleaning"], sale=True, new_arr=True, img_kw="robot-vacuum"),
            _make("Handheld Vacuum Cordless", 3, 12, 4999, 7999, 37.5, tags=["appliance","cleaning"], sale=True, img_kw="handheld-vacuum"),
            _make("Iron Press Steam 2200W", 3, 5, 2499, 3999, 37.5, tags=["appliance","laundry"], sale=True, img_kw="steam-iron"),
            _make("Ceiling Fan Decorative 48 inch", 3, 6, 3499, 4999, 30.0, tags=["appliance","cooling"], sale=True, img_kw="ceiling-fan"),
            _make("Room Heater Oil Filled", 3, 12, 5999, 8999, 33.3, tags=["appliance","heating"], sale=True, img_kw="room-heater"),
            _make("Dish Drying Rack Steel", 3, 8, 699, 1299, 46.2, tags=["kitchen","organization"], sale=True, img_kw="dish-rack"),
            _make("Spice Rack Revolving 16 Jars", 3, 8, 899, 1699, 47.1, tags=["kitchen","organization"], sale=True, img_kw="spice-rack"),
            _make("Bathroom Organizer Wall Mount", 3, 8, 499, 999, 50.1, tags=["bathroom","storage"], sale=True, img_kw="bath-organizer"),
            _make("Shoe Rack 6 Tier Metal", 3, 8, 1299, 2499, 48.0, tags=["storage","organization"], sale=True, img_kw="shoe-rack"),
            _make("Wardrobe 3 Door with Mirror", 3, 6, 14999, 22999, 34.8, tags=["furniture","bedroom"], sale=True, img_kw="wardrobe"),
            _make("Study Table with Drawer", 3, 6, 5999, 8999, 33.3, tags=["furniture","study"], sale=True, img_kw="study-table"),
            _make("TV Stand Entertainment Unit", 3, 6, 6999, 9999, 30.0, tags=["furniture","living"], sale=True, img_kw="tv-stand"),
            _make("Coffee Table Glass Top", 3, 6, 4999, 7999, 37.5, tags=["furniture","living"], sale=True, img_kw="coffee-table"),
            _make("Kitchen Chimney Auto Clean", 3, 6, 12999, 18999, 31.6, tags=["kitchen","appliance"], sale=True, img_kw="kitchen-chimney"),
            _make("Food Processor 1000W", 3, 5, 5999, 8999, 33.3, tags=["kitchen","appliance"], sale=True, img_kw="food-processor"),
            _make("Toaster 4 Slice Pop-Up", 3, 5, 1999, 3499, 42.9, tags=["kitchen","breakfast"], sale=True, img_kw="toaster"),
            _make("Hand Blender 600W", 3, 5, 1499, 2499, 40.0, tags=["kitchen","appliance"], sale=True, img_kw="hand-blender"),
            _make("Pressure Cooker 5L Steel", 3, 8, 1999, 2999, 33.3, tags=["kitchen","cooking"], sale=True, img_kw="pressure-cooker"),
            _make("Cast Iron Tawa 12 inch", 3, 8, 799, 1499, 46.7, tags=["kitchen","cooking"], sale=True, img_kw="cast-iron-tawa"),
            _make("Door Mat Welcome Coir", 3, 8, 299, 599, 50.1, tags=["decor","entrance"], sale=True, img_kw="door-mat"),
            _make("Artificial Plant Set of 4", 3, 8, 699, 1299, 46.2, tags=["decor","plants"], sale=True, img_kw="artificial-plants"),
            _make("Photo Frame Collage Set 8pc", 3, 8, 899, 1799, 50.0, tags=["decor","frames"], sale=True, img_kw="photo-frames"),
            _make("Essential Oil Diffuser LED", 3, 5, 1499, 2999, 50.0, tags=["decor","wellness"], sale=True, img_kw="oil-diffuser"),
            _make("Smart WiFi Plug 4 Pack", 3, 6, 1999, 3499, 42.9, tags=["smart-home","plug"], sale=True, new_arr=True, img_kw="smart-plug"),
        ]
        products.extend(home)

        # ---------- BOOKS (cat=4) 50 products ----------
        books = [
            _make("Atomic Habits by James Clear", 4, None, 399, 799, 50.1, tags=["self-help","bestseller"], sale=True, feat=True, img_kw="atomic-habits"),
            _make("The Psychology of Money", 4, None, 349, 599, 41.7, tags=["finance","self-help"], sale=True, img_kw="psychology-money"),
            _make("Rich Dad Poor Dad", 4, None, 299, 499, 40.1, tags=["finance","classic"], sale=True, img_kw="rich-dad"),
            _make("Sapiens by Yuval Noah Harari", 4, None, 449, 699, 35.8, tags=["history","nonfiction"], sale=True, img_kw="sapiens-book"),
            _make("Ikigai The Japanese Secret", 4, None, 299, 499, 40.1, tags=["self-help","japanese"], sale=True, img_kw="ikigai-book"),
            _make("Think and Grow Rich", 4, None, 199, 399, 50.1, tags=["self-help","classic"], sale=True, img_kw="think-grow-rich"),
            _make("The Alchemist by Paulo Coelho", 4, None, 299, 499, 40.1, tags=["fiction","classic"], sale=True, img_kw="alchemist-book"),
            _make("Harry Potter Complete Box Set", 4, None, 2999, 4999, 40.0, tags=["fiction","fantasy","boxset"], sale=True, feat=True, img_kw="harry-potter"),
            _make("To Kill a Mockingbird", 4, None, 349, 599, 41.7, tags=["fiction","classic"], sale=True, img_kw="mockingbird-book"),
            _make("1984 by George Orwell", 4, None, 249, 399, 37.6, tags=["fiction","dystopian"], sale=True, img_kw="1984-book"),
            _make("The Great Gatsby", 4, None, 199, 349, 43.0, tags=["fiction","classic"], sale=True, img_kw="great-gatsby"),
            _make("Deep Work by Cal Newport", 4, None, 399, 599, 33.4, tags=["productivity","self-help"], sale=True, img_kw="deep-work"),
            _make("Thinking Fast and Slow", 4, None, 449, 699, 35.8, tags=["psychology","nonfiction"], sale=True, img_kw="thinking-fast"),
            _make("The 7 Habits of Highly Effective People", 4, None, 399, 599, 33.4, tags=["self-help","leadership"], sale=True, img_kw="7-habits"),
            _make("How to Win Friends and Influence", 4, None, 299, 499, 40.1, tags=["self-help","communication"], sale=True, img_kw="win-friends"),
            _make("Zero to One by Peter Thiel", 4, None, 399, 599, 33.4, tags=["business","startup"], sale=True, img_kw="zero-to-one"),
            _make("The Lean Startup", 4, None, 449, 699, 35.8, tags=["business","startup"], sale=True, img_kw="lean-startup"),
            _make("Clean Code by Robert Martin", 4, None, 2999, tags=["programming","technical"], img_kw="clean-code"),
            _make("JavaScript The Good Parts", 4, None, 1499, 1999, 25.0, tags=["programming","javascript"], sale=True, img_kw="js-good-parts"),
            _make("Head First Design Patterns", 4, None, 3499, tags=["programming","patterns"], img_kw="design-patterns"),
            _make("Python Crash Course", 4, None, 2499, 2999, 16.7, tags=["programming","python"], sale=True, img_kw="python-crash"),
            _make("Introduction to Algorithms CLRS", 4, None, 4999, tags=["programming","academic"], img_kw="clrs-book"),
            _make("Database System Concepts", 4, None, 3999, tags=["programming","database"], img_kw="database-book"),
            _make("Operating System Concepts Galvin", 4, None, 3499, tags=["programming","academic"], img_kw="os-book"),
            _make("Cracking the Coding Interview", 4, None, 2999, tags=["programming","interview"], feat=True, img_kw="cracking-interview"),
            _make("System Design Interview", 4, None, 2499, tags=["programming","interview"], img_kw="system-design"),
            _make("The Art of War - Sun Tzu", 4, None, 149, 299, 50.2, tags=["philosophy","classic"], sale=True, img_kw="art-of-war"),
            _make("Meditations by Marcus Aurelius", 4, None, 199, 399, 50.1, tags=["philosophy","stoicism"], sale=True, img_kw="meditations"),
            _make("Man's Search for Meaning", 4, None, 249, 399, 37.6, tags=["philosophy","memoir"], sale=True, img_kw="mans-search"),
            _make("Gone Girl by Gillian Flynn", 4, None, 349, 499, 30.1, tags=["fiction","thriller"], sale=True, img_kw="gone-girl"),
            _make("The Girl on the Train", 4, None, 299, 499, 40.1, tags=["fiction","thriller"], sale=True, img_kw="girl-train"),
            _make("Sherlock Holmes Complete", 4, None, 599, 999, 40.0, tags=["fiction","mystery","classic"], sale=True, img_kw="sherlock-book"),
            _make("Percy Jackson Lightning Thief", 4, None, 399, 599, 33.4, tags=["fiction","fantasy","ya"], sale=True, img_kw="percy-jackson"),
            _make("Diary of a Wimpy Kid Box Set", 4, None, 1999, 2999, 33.3, tags=["fiction","kids","boxset"], sale=True, img_kw="wimpy-kid"),
            _make("The Subtle Art of Not Giving", 4, None, 349, 599, 41.7, tags=["self-help","modern"], sale=True, img_kw="subtle-art"),
            _make("Wings of Fire by APJ Abdul Kalam", 4, None, 199, 349, 43.0, tags=["biography","inspiration"], sale=True, img_kw="wings-fire"),
            _make("Steve Jobs Biography Walter Isaacson", 4, None, 499, 799, 37.5, tags=["biography","tech"], sale=True, img_kw="steve-jobs"),
            _make("Elon Musk Biography", 4, None, 599, 899, 33.4, tags=["biography","tech"], sale=True, img_kw="elon-musk-bio"),
            _make("A Brief History of Time Hawking", 4, None, 399, 699, 42.9, tags=["science","physics"], sale=True, img_kw="brief-history"),
            _make("The Selfish Gene by Dawkins", 4, None, 449, 699, 35.8, tags=["science","biology"], sale=True, img_kw="selfish-gene"),
            _make("Cosmos by Carl Sagan", 4, None, 399, 599, 33.4, tags=["science","astronomy"], sale=True, img_kw="cosmos-sagan"),
            _make("Marvel Encyclopedia", 4, None, 1999, tags=["comics","encyclopedia"], img_kw="marvel-encyclopedia"),
            _make("Naruto Box Set 1 Manga", 4, None, 3999, tags=["manga","anime"], feat=True, img_kw="naruto-manga"),
            _make("One Piece Volume 1 Manga", 4, None, 499, tags=["manga","anime"], img_kw="one-piece"),
            _make("NCERT Mathematics Class 12", 4, None, 299, tags=["academic","math"], img_kw="ncert-math"),
            _make("NCERT Physics Class 12", 4, None, 299, tags=["academic","physics"], img_kw="ncert-physics"),
            _make("Oxford English Dictionary", 4, None, 999, 1499, 33.4, tags=["reference","dictionary"], sale=True, img_kw="oxford-dict"),
            _make("Children's Picture Atlas", 4, None, 599, 999, 40.0, tags=["kids","geography"], sale=True, img_kw="picture-atlas"),
            _make("Coloring Book for Adults Mandala", 4, None, 299, 599, 50.1, tags=["art","relaxation"], sale=True, img_kw="mandala-coloring"),
            _make("Recipe Book Indian Cooking", 4, None, 499, 799, 37.5, tags=["cooking","indian"], sale=True, img_kw="indian-cooking"),
        ]
        products.extend(books)

        # ---------- SPORTS & FITNESS (cat=5) 50 products ----------
        sports = [
            _make("Nike Pro Training Mat Yoga", 5, 3, 2995, tags=["fitness","yoga"], img_kw="yoga-mat"),
            _make("Nike Mercurial Football Boots", 5, 3, 9995, tags=["football","shoes"], feat=True, img_kw="mercurial-boots"),
            _make("Nike Running Shoes Pegasus 40", 5, 3, 8995, 10995, 18.2, tags=["running","shoes"], sale=True, img_kw="pegasus-40"),
            _make("Nike Gym Duffle Bag", 5, 3, 2495, tags=["bag","gym"], img_kw="nike-gym-bag"),
            _make("Nike Shin Guards", 5, 3, 799, 1299, 38.5, tags=["football","protection"], sale=True, img_kw="shin-guards"),
            _make("Adidas Predator Football", 5, 4, 3999, tags=["football","ball"], img_kw="adidas-football"),
            _make("Adidas Tennis Racket Carbon", 5, 4, 5999, 7999, 25.0, tags=["tennis","racket"], sale=True, img_kw="tennis-racket"),
            _make("Adidas Gym Gloves Padded", 5, 4, 699, 1299, 46.2, tags=["gym","gloves"], sale=True, img_kw="gym-gloves"),
            _make("Adidas Running Armband Phone", 5, 4, 499, 999, 50.1, tags=["running","accessory"], sale=True, img_kw="running-armband"),
            _make("Adidas Cricket Bat Kashmir Willow", 5, 4, 2999, 4999, 40.0, tags=["cricket","bat"], sale=True, img_kw="cricket-bat"),
            _make("Puma Gym Shoes Training", 5, 7, 3499, 5999, 41.7, tags=["gym","shoes"], sale=True, img_kw="gym-shoes"),
            _make("Puma Sports Water Bottle 750ml", 5, 7, 499, 899, 44.5, tags=["fitness","bottle"], sale=True, img_kw="sports-bottle"),
            _make("Treadmill Foldable Home Gym", 5, 8, 24999, 39999, 37.5, tags=["gym","cardio"], sale=True, feat=True, img_kw="treadmill"),
            _make("Dumbbell Set 20kg Adjustable", 5, 8, 2999, 4999, 40.0, tags=["gym","weights"], sale=True, img_kw="dumbbell-set"),
            _make("Pull-Up Bar Doorway", 5, 8, 999, 1999, 50.0, tags=["gym","bodyweight"], sale=True, img_kw="pull-up-bar"),
            _make("Resistance Bands Set of 5", 5, 8, 499, 999, 50.1, tags=["fitness","stretching"], sale=True, img_kw="resistance-bands"),
            _make("Foam Roller Recovery", 5, 8, 699, 1299, 46.2, tags=["fitness","recovery"], sale=True, img_kw="foam-roller"),
            _make("Jump Rope Speed Wire", 5, 8, 299, 599, 50.1, tags=["fitness","cardio"], sale=True, img_kw="jump-rope"),
            _make("Exercise Ball 65cm Anti Burst", 5, 8, 599, 1199, 50.0, tags=["fitness","core"], sale=True, img_kw="exercise-ball"),
            _make("Yoga Block Set of 2 EVA", 5, 8, 399, 799, 50.1, tags=["yoga","flexibility"], sale=True, img_kw="yoga-blocks"),
            _make("Badminton Racket Set of 2", 5, 8, 799, 1499, 46.7, tags=["badminton","racket"], sale=True, img_kw="badminton-rackets"),
            _make("Shuttlecock Pack of 10", 5, 8, 299, 499, 40.1, tags=["badminton","shuttle"], sale=True, img_kw="shuttlecocks"),
            _make("Table Tennis Set with Net", 5, 8, 999, 1999, 50.0, tags=["table-tennis","indoor"], sale=True, img_kw="table-tennis-set"),
            _make("Cycling Helmet Adult Safety", 5, 8, 999, 1999, 50.0, tags=["cycling","safety"], sale=True, img_kw="cycling-helmet"),
            _make("Bicycle Mountain Gear 21 Speed", 5, 8, 14999, 21999, 31.8, tags=["cycling","outdoor"], sale=True, feat=True, img_kw="mountain-bike"),
            _make("Boxing Gloves 12oz Leather", 5, 8, 1999, 3499, 42.9, tags=["boxing","martial-arts"], sale=True, img_kw="boxing-gloves"),
            _make("Punching Bag Heavy 70lb", 5, 8, 4999, 7999, 37.5, tags=["boxing","training"], sale=True, img_kw="punching-bag"),
            _make("Swimming Goggles Anti Fog", 5, 8, 399, 799, 50.1, tags=["swimming","eyewear"], sale=True, img_kw="swim-goggles"),
            _make("Swim Cap Silicone", 5, 8, 199, 399, 50.1, tags=["swimming","accessory"], sale=True, img_kw="swim-cap"),
            _make("Cricket Ball Leather SG", 5, 8, 499, 899, 44.5, tags=["cricket","ball"], sale=True, img_kw="cricket-ball"),
            _make("Camping Tent 4 Person", 5, 8, 4999, 7999, 37.5, tags=["camping","outdoor"], sale=True, img_kw="camping-tent"),
            _make("Sleeping Bag Warm Weather", 5, 8, 1999, 3499, 42.9, tags=["camping","sleeping"], sale=True, img_kw="sleeping-bag"),
            _make("Hiking Backpack 50L", 5, 4, 3999, 5999, 33.3, tags=["hiking","outdoor"], sale=True, img_kw="hiking-backpack"),
            _make("Trekking Poles Pair Carbon", 5, 8, 1999, 2999, 33.3, tags=["hiking","trekking"], sale=True, img_kw="trekking-poles"),
            _make("Protein Powder Whey 1kg", 5, 15, 1499, 2499, 40.0, tags=["nutrition","supplement"], sale=True, img_kw="protein-powder"),
            _make("BCAA Energy Drink Mix", 5, 15, 999, 1499, 33.4, tags=["nutrition","energy"], sale=True, img_kw="bcaa-drink"),
            _make("Creatine Monohydrate 250g", 5, 15, 799, 1299, 38.5, tags=["nutrition","supplement"], sale=True, img_kw="creatine"),
            _make("Shaker Bottle 700ml", 5, 8, 299, 599, 50.1, tags=["nutrition","accessories"], sale=True, img_kw="shaker-bottle"),
            _make("Skipping Rope Digital Count", 5, 8, 499, 999, 50.1, tags=["fitness","cardio"], sale=True, img_kw="digital-skiprope"),
            _make("Ab Roller Wheel Core", 5, 8, 499, 999, 50.1, tags=["fitness","core"], sale=True, img_kw="ab-roller"),
            _make("Wrist Wraps Gym Support", 5, 8, 299, 599, 50.1, tags=["gym","support"], sale=True, img_kw="wrist-wraps"),
            _make("Knee Sleeves Compression Pair", 5, 8, 699, 1299, 46.2, tags=["gym","support"], sale=True, img_kw="knee-sleeves"),
            _make("Gym Bench Adjustable Flat", 5, 8, 5999, 8999, 33.3, tags=["gym","equipment"], sale=True, img_kw="gym-bench"),
            _make("Kettlebell 16kg Cast Iron", 5, 8, 1499, 2499, 40.0, tags=["gym","weights"], sale=True, img_kw="kettlebell"),
            _make("Battle Ropes 30ft", 5, 8, 2999, 4999, 40.0, tags=["gym","cardio"], sale=True, img_kw="battle-ropes"),
            _make("Basketball Spalding Indoor", 5, 4, 1999, 2999, 33.3, tags=["basketball","indoor"], sale=True, img_kw="basketball"),
            _make("Volleyball Mikasa Official", 5, 8, 1499, 2499, 40.0, tags=["volleyball","indoor"], sale=True, img_kw="volleyball"),
            _make("Football Boots Astro Turf", 5, 7, 2999, 4999, 40.0, tags=["football","shoes"], sale=True, img_kw="astro-boots"),
            _make("Golf Club Set Beginner", 5, 8, 14999, 24999, 40.0, tags=["golf","outdoor"], sale=True, img_kw="golf-set"),
            _make("Skateboard Complete 31 inch", 5, 8, 1999, 3499, 42.9, tags=["skating","outdoor"], sale=True, new_arr=True, img_kw="skateboard"),
        ]
        products.extend(sports)

        # ---------- BEAUTY & PERSONAL CARE (cat=6) 50 products ----------
        beauty = [
            _make("Lakme 9to5 Primer + Matte Foundation", 6, 14, 599, 899, 33.4, tags=["makeup","foundation"], sale=True, feat=True, img_kw="lakme-foundation"),
            _make("Lakme Absolute Skin Natural Mousse", 6, 14, 799, tags=["makeup","mousse"], img_kw="lakme-mousse"),
            _make("Lakme Lipstick Matte Red", 6, 14, 349, 599, 41.7, tags=["makeup","lipstick"], sale=True, img_kw="lakme-lipstick"),
            _make("Lakme Kajal Deep Black", 6, 14, 199, 299, 33.4, tags=["makeup","kajal"], sale=True, img_kw="lakme-kajal"),
            _make("Lakme Sun Expert SPF 50", 6, 14, 399, 599, 33.4, tags=["skincare","sunscreen"], sale=True, img_kw="lakme-sunscreen"),
            _make("Vitamin C Serum 30ml", 6, 14, 499, 999, 50.1, tags=["skincare","serum"], sale=True, feat=True, img_kw="vitamin-c-serum"),
            _make("Retinol Night Cream 50ml", 6, 14, 699, 1299, 46.2, tags=["skincare","anti-aging"], sale=True, img_kw="retinol-cream"),
            _make("Hyaluronic Acid Moisturizer", 6, 14, 599, 999, 40.0, tags=["skincare","moisturizer"], sale=True, img_kw="hyaluronic-acid"),
            _make("Niacinamide Serum 10%", 6, 14, 399, 799, 50.1, tags=["skincare","serum"], sale=True, img_kw="niacinamide"),
            _make("Charcoal Face Wash 150ml", 6, 14, 249, 499, 50.1, tags=["skincare","facewash"], sale=True, img_kw="charcoal-facewash"),
            _make("Aloe Vera Gel Pure 300ml", 6, 15, 199, 399, 50.1, tags=["skincare","natural"], sale=True, img_kw="aloe-vera-gel"),
            _make("Rose Water Toner 200ml", 6, 14, 149, 299, 50.2, tags=["skincare","toner"], sale=True, img_kw="rose-water"),
            _make("Hair Oil Argan 200ml", 6, 14, 499, 799, 37.5, tags=["haircare","oil"], sale=True, img_kw="argan-oil"),
            _make("Shampoo Anti-Dandruff 400ml", 6, 15, 349, 599, 41.7, tags=["haircare","shampoo"], sale=True, img_kw="anti-dandruff"),
            _make("Conditioner Keratin Smooth 300ml", 6, 14, 299, 499, 40.1, tags=["haircare","conditioner"], sale=True, img_kw="keratin-conditioner"),
            _make("Hair Dryer 2200W Professional", 6, 5, 2499, 3999, 37.5, tags=["haircare","appliance"], sale=True, img_kw="hair-dryer"),
            _make("Hair Straightener Ceramic", 6, 5, 1999, 2999, 33.3, tags=["haircare","styling"], sale=True, img_kw="hair-straightener"),
            _make("Electric Trimmer Men", 6, 5, 1499, 2499, 40.0, tags=["grooming","men"], sale=True, img_kw="electric-trimmer"),
            _make("Beard Oil Growth 50ml", 6, 14, 399, 699, 42.9, tags=["grooming","men"], sale=True, img_kw="beard-oil"),
            _make("Face Mask Sheet Pack of 10", 6, 14, 399, 799, 50.1, tags=["skincare","mask"], sale=True, img_kw="face-mask-sheet"),
            _make("Eye Cream Dark Circle 15ml", 6, 14, 599, 999, 40.0, tags=["skincare","eye-cream"], sale=True, img_kw="eye-cream"),
            _make("Lip Balm SPF 15 Strawberry", 6, 14, 99, 199, 50.3, tags=["skincare","lip"], sale=True, img_kw="lip-balm"),
            _make("Nail Polish Set 12 Colors", 6, 14, 399, 799, 50.1, tags=["nails","colors"], sale=True, img_kw="nail-polish-set"),
            _make("Makeup Brush Set 12 Pcs", 6, 14, 499, 999, 50.1, tags=["makeup","brushes"], sale=True, img_kw="makeup-brushes"),
            _make("Compact Powder Matte Finish", 6, 14, 249, 499, 50.1, tags=["makeup","powder"], sale=True, img_kw="compact-powder"),
            _make("Mascara Waterproof Volume", 6, 14, 349, 599, 41.7, tags=["makeup","mascara"], sale=True, img_kw="mascara"),
            _make("Eyeshadow Palette 18 Shades", 6, 14, 699, 1299, 46.2, tags=["makeup","eyeshadow"], sale=True, img_kw="eyeshadow-palette"),
            _make("Perfume Men Eau De Toilette 100ml", 6, 10, 3999, 5999, 33.3, tags=["fragrance","men"], sale=True, img_kw="mens-perfume"),
            _make("Perfume Women Eau De Parfum 100ml", 6, 10, 4999, 7999, 37.5, tags=["fragrance","women"], sale=True, img_kw="womens-perfume"),
            _make("Deodorant Spray Combo Pack 3", 6, 7, 499, 899, 44.5, tags=["fragrance","combo"], sale=True, img_kw="deo-combo"),
            _make("Body Lotion Moisturizing 400ml", 6, 15, 299, 499, 40.1, tags=["skincare","body"], sale=True, img_kw="body-lotion"),
            _make("Hand Cream Shea Butter 75ml", 6, 14, 199, 349, 43.0, tags=["skincare","hand"], sale=True, img_kw="hand-cream"),
            _make("Foot Cream Cracked Heels 100ml", 6, 14, 149, 299, 50.2, tags=["skincare","foot"], sale=True, img_kw="foot-cream"),
            _make("Bath Bomb Set of 6 Fizzy", 6, 14, 499, 999, 50.1, tags=["bath","relaxation"], sale=True, img_kw="bath-bombs"),
            _make("Body Scrub Coffee 200g", 6, 14, 399, 699, 42.9, tags=["skincare","exfoliation"], sale=True, img_kw="coffee-scrub"),
            _make("Teeth Whitening Strips 14 Day", 6, 15, 999, 1999, 50.0, tags=["dental","whitening"], sale=True, img_kw="whitening-strips"),
            _make("Electric Toothbrush Sonic", 6, 5, 2499, 3999, 37.5, tags=["dental","electric"], sale=True, img_kw="electric-toothbrush"),
            _make("Hair Serum Frizz Control", 6, 14, 349, 599, 41.7, tags=["haircare","serum"], sale=True, img_kw="hair-serum"),
            _make("Dry Shampoo Spray 200ml", 6, 14, 399, 699, 42.9, tags=["haircare","dry-shampoo"], sale=True, img_kw="dry-shampoo"),
            _make("Curling Iron 32mm Barrel", 6, 5, 1799, 2999, 40.0, tags=["haircare","styling"], sale=True, img_kw="curling-iron"),
            _make("Makeup Remover Micellar Water 400ml", 6, 14, 299, 499, 40.1, tags=["skincare","cleansing"], sale=True, img_kw="micellar-water"),
            _make("Setting Spray Matte Finish", 6, 14, 399, 699, 42.9, tags=["makeup","setting"], sale=True, img_kw="setting-spray"),
            _make("BB Cream SPF 30 Light", 6, 14, 349, 599, 41.7, tags=["makeup","bb-cream"], sale=True, img_kw="bb-cream"),
            _make("Facial Roller Jade Stone", 6, 14, 299, 599, 50.1, tags=["skincare","tool"], sale=True, img_kw="jade-roller"),
            _make("Pedicure Kit 18 Tools Steel", 6, 14, 599, 999, 40.0, tags=["grooming","tools"], sale=True, img_kw="pedicure-kit"),
            _make("Cologne Fresh Aqua Men 150ml", 6, 7, 799, 1299, 38.5, tags=["fragrance","men"], sale=True, img_kw="cologne-aqua"),
            _make("Sunscreen SPF 50 Gel 100ml", 6, 14, 449, 699, 35.8, tags=["skincare","sun-protection"], sale=True, img_kw="sunscreen-gel"),
            _make("Under Eye Patches Gold 30 Pairs", 6, 14, 499, 999, 50.1, tags=["skincare","eye"], sale=True, new_arr=True, img_kw="eye-patches"),
            _make("Hair Mask Keratin Repair 200ml", 6, 14, 399, 699, 42.9, tags=["haircare","treatment"], sale=True, img_kw="hair-mask"),
            _make("Makeup Vanity Mirror LED", 6, 14, 1499, 2499, 40.0, tags=["makeup","mirror"], sale=True, img_kw="vanity-mirror"),
        ]
        products.extend(beauty)

        # ---------- TOYS & GAMES (cat=7) 50 products ----------
        toys = [
            _make("LEGO City Police Station 743 Pcs", 7, None, 4999, 6999, 28.6, tags=["lego","building"], sale=True, feat=True, img_kw="lego-police"),
            _make("LEGO Technic Lamborghini", 7, None, 34999, tags=["lego","premium","car"], prem=True, img_kw="lego-lambo"),
            _make("LEGO Star Wars Millennium Falcon", 7, None, 14999, tags=["lego","star-wars"], feat=True, img_kw="lego-falcon"),
            _make("LEGO Friends Heartlake City", 7, None, 2999, 4499, 33.3, tags=["lego","friends"], sale=True, img_kw="lego-friends"),
            _make("LEGO Duplo My First Farm", 7, None, 1999, 2999, 33.3, tags=["lego","toddler"], sale=True, img_kw="lego-duplo"),
            _make("Hot Wheels 20 Car Pack", 7, None, 1999, 2999, 33.3, tags=["cars","toys"], sale=True, img_kw="hot-wheels"),
            _make("Hot Wheels Track Builder Loop", 7, None, 2499, 3499, 28.6, tags=["cars","track"], sale=True, img_kw="hot-wheels-track"),
            _make("Barbie Dreamhouse Dollhouse", 7, None, 9999, 14999, 33.3, tags=["barbie","dollhouse"], sale=True, feat=True, img_kw="barbie-dreamhouse"),
            _make("Barbie Career Doll Doctor", 7, None, 999, 1499, 33.4, tags=["barbie","doll"], sale=True, img_kw="barbie-doctor"),
            _make("Nerf Elite 2.0 Blaster", 7, None, 1999, 2999, 33.3, tags=["nerf","outdoor"], sale=True, img_kw="nerf-blaster"),
            _make("Nerf Rival Kronos Blaster", 7, None, 2999, 4499, 33.3, tags=["nerf","action"], sale=True, img_kw="nerf-kronos"),
            _make("Play-Doh Super Color Pack 20", 7, None, 999, 1499, 33.4, tags=["playdoh","creative"], sale=True, img_kw="playdoh-pack"),
            _make("Monopoly Classic Board Game", 7, None, 999, 1499, 33.4, tags=["board-game","classic"], sale=True, img_kw="monopoly"),
            _make("Scrabble Original Board Game", 7, None, 799, 1299, 38.5, tags=["board-game","word"], sale=True, img_kw="scrabble"),
            _make("Chess Set Wooden Premium", 7, None, 1499, tags=["board-game","chess"], img_kw="chess-set"),
            _make("UNO Card Game Classic", 7, None, 199, 399, 50.1, tags=["card-game","classic"], sale=True, img_kw="uno-cards"),
            _make("Jenga Classic Tower Game", 7, None, 599, 999, 40.0, tags=["board-game","balance"], sale=True, img_kw="jenga"),
            _make("Rubik's Cube 3x3 Original", 7, None, 299, 599, 50.1, tags=["puzzle","classic"], sale=True, img_kw="rubiks-cube"),
            _make("Jigsaw Puzzle 1000 Pcs Landscape", 7, None, 699, 1199, 41.7, tags=["puzzle","landscape"], sale=True, img_kw="jigsaw-puzzle"),
            _make("RC Car Off-Road 4WD", 7, None, 2999, 4999, 40.0, tags=["rc","car","outdoor"], sale=True, img_kw="rc-car"),
            _make("RC Helicopter 3.5 Channel", 7, None, 1999, 3499, 42.9, tags=["rc","helicopter"], sale=True, img_kw="rc-helicopter"),
            _make("Drone Mini Camera HD", 7, None, 4999, 7999, 37.5, tags=["drone","camera","toy"], sale=True, img_kw="mini-drone"),
            _make("Nintendo Switch Lite", 7, 5, 19999, tags=["gaming","console"], feat=True, img_kw="switch-lite"),
            _make("Gaming Headset RGB Wired", 7, 8, 1499, 2499, 40.0, tags=["gaming","headset"], sale=True, img_kw="gaming-headset"),
            _make("Minecraft Action Figure Set", 7, None, 1499, 2499, 40.0, tags=["action-figure","gaming"], sale=True, img_kw="minecraft-figures"),
            _make("Marvel Avengers Action Figure", 7, None, 999, 1499, 33.4, tags=["action-figure","marvel"], sale=True, img_kw="avengers-figure"),
            _make("Transformers Optimus Prime", 7, None, 2499, 3999, 37.5, tags=["action-figure","transformers"], sale=True, img_kw="transformers"),
            _make("Dinosaur T-Rex Walking Robot", 7, None, 1999, 2999, 33.3, tags=["robots","dinosaur"], sale=True, img_kw="dino-robot"),
            _make("Baby Building Blocks 50 Pcs", 7, None, 499, 999, 50.1, tags=["baby","building"], sale=True, img_kw="baby-blocks"),
            _make("Musical Piano Mat for Kids", 7, None, 799, 1499, 46.7, tags=["musical","baby"], sale=True, img_kw="piano-mat"),
            _make("Soft Toy Teddy Bear 3 Feet", 7, None, 999, 1999, 50.0, tags=["soft-toy","teddy"], sale=True, img_kw="teddy-bear"),
            _make("Kitchen Playset 42 Pcs", 7, None, 1499, 2499, 40.0, tags=["pretend-play","kitchen"], sale=True, img_kw="kitchen-playset"),
            _make("Doctor Kit Pretend Play 16 Pcs", 7, None, 599, 999, 40.0, tags=["pretend-play","doctor"], sale=True, img_kw="doctor-kit"),
            _make("Art Set 150 Pcs Deluxe", 7, None, 999, 1999, 50.0, tags=["art","creative"], sale=True, img_kw="art-set"),
            _make("Crayola Crayons Box 120 Colors", 7, None, 699, 1199, 41.7, tags=["art","coloring"], sale=True, img_kw="crayola-box"),
            _make("Telescope Kids Science 60mm", 7, None, 2999, 4999, 40.0, tags=["science","educational"], sale=True, img_kw="kids-telescope"),
            _make("Microscope Kit 1200x Students", 7, None, 1999, 2999, 33.3, tags=["science","educational"], sale=True, img_kw="microscope-kit"),
            _make("Chemistry Experiment Kit", 7, None, 1499, 2499, 40.0, tags=["science","experiment"], sale=True, img_kw="chemistry-kit"),
            _make("Coding Robot Educational", 7, None, 3999, 5999, 33.3, tags=["stem","coding"], sale=True, new_arr=True, img_kw="coding-robot"),
            _make("Magnetic Tiles Building 100 Pcs", 7, None, 1999, 3499, 42.9, tags=["building","magnetic"], sale=True, img_kw="magnetic-tiles"),
            _make("Water Gun Super Soaker", 7, None, 499, 999, 50.1, tags=["outdoor","water"], sale=True, img_kw="water-gun"),
            _make("Trampoline 55 inch Kids Indoor", 7, None, 4999, 7999, 37.5, tags=["outdoor","active"], sale=True, img_kw="trampoline"),
            _make("Swing Set Metal Outdoor", 7, None, 9999, 14999, 33.3, tags=["outdoor","garden"], sale=True, img_kw="swing-set"),
            _make("Sand Pit with Cover", 7, None, 2999, 4999, 40.0, tags=["outdoor","toddler"], sale=True, img_kw="sand-pit"),
            _make("Bicycle Kids 16 inch Training Wheels", 7, None, 5999, 8999, 33.3, tags=["cycling","kids"], sale=True, img_kw="kids-bicycle"),
            _make("Scooter 3 Wheel Foldable", 7, None, 1999, 3499, 42.9, tags=["outdoor","kids"], sale=True, img_kw="kids-scooter"),
            _make("Card Games Bundle Exploding Kittens", 7, None, 1499, 2499, 40.0, tags=["card-game","party"], sale=True, img_kw="exploding-kittens"),
            _make("Risk Strategy Board Game", 7, None, 1999, 2999, 33.3, tags=["board-game","strategy"], sale=True, img_kw="risk-game"),
            _make("Catan Board Game", 7, None, 2499, 3499, 28.6, tags=["board-game","strategy"], sale=True, img_kw="catan-game"),
            _make("Ticket to Ride Board Game", 7, None, 2999, 3999, 25.0, tags=["board-game","family"], sale=True, img_kw="ticket-to-ride"),
        ]
        products.extend(toys)

        # ---------- GROCERIES (cat=8) 50 products ----------
        groc = [
            _make("Basmati Rice 5kg Premium Aged", 8, 15, 499, 699, 28.6, tags=["rice","staples"], sale=True, img_kw="basmati-rice"),
            _make("Whole Wheat Atta 10kg", 8, 15, 399, 499, 20.0, tags=["flour","staples"], sale=True, img_kw="wheat-atta"),
            _make("Toor Dal 1kg", 8, 15, 149, 199, 25.1, tags=["dal","pulses"], sale=True, img_kw="toor-dal"),
            _make("Moong Dal Yellow 1kg", 8, 15, 139, 179, 22.3, tags=["dal","pulses"], sale=True, img_kw="moong-dal"),
            _make("Refined Sunflower Oil 5L", 8, 15, 599, 799, 25.0, tags=["oil","cooking"], sale=True, img_kw="sunflower-oil"),
            _make("Extra Virgin Olive Oil 1L", 8, 15, 699, 999, 30.0, tags=["oil","premium"], sale=True, img_kw="olive-oil"),
            _make("Sugar White 5kg", 8, 15, 249, 299, 16.7, tags=["sugar","staples"], sale=True, img_kw="white-sugar"),
            _make("Salt Iodised 1kg Pack of 3", 8, 15, 60, 90, 33.3, tags=["salt","staples"], sale=True, img_kw="iodised-salt"),
            _make("Tea Leaves Premium 500g", 8, 15, 299, 399, 25.1, tags=["tea","beverages"], sale=True, img_kw="tea-leaves"),
            _make("Coffee Bean Arabica 250g", 8, 15, 399, 599, 33.4, tags=["coffee","premium"], sale=True, img_kw="arabica-coffee"),
            _make("Instant Coffee Nescafe 200g", 8, 15, 449, 599, 25.0, tags=["coffee","instant"], sale=True, img_kw="nescafe"),
            _make("Green Tea Honey Lemon 25 Bags", 8, 15, 199, 299, 33.4, tags=["tea","healthy"], sale=True, img_kw="green-tea"),
            _make("Milk Full Cream 1L Pack of 6", 8, 15, 330, tags=["milk","dairy"], img_kw="full-cream-milk"),
            _make("Curd Yogurt 400g Pack of 4", 8, 15, 180, tags=["curd","dairy"], img_kw="curd-yogurt"),
            _make("Cheese Slices Pack of 10", 8, 15, 199, 249, 20.1, tags=["cheese","dairy"], sale=True, img_kw="cheese-slices"),
            _make("Butter Amul 500g", 8, 15, 265, tags=["butter","dairy"], img_kw="amul-butter"),
            _make("Maggi Noodles Pack of 12", 8, 15, 168, tags=["noodles","instant"], img_kw="maggi-noodles"),
            _make("Pasta Penne 500g", 8, 15, 99, 149, 33.6, tags=["pasta","italian"], sale=True, img_kw="penne-pasta"),
            _make("Tomato Ketchup 1kg Squeeze", 8, 15, 129, 179, 27.9, tags=["sauce","condiment"], sale=True, img_kw="tomato-ketchup"),
            _make("Soy Sauce 200ml", 8, 15, 79, 129, 38.8, tags=["sauce","asian"], sale=True, img_kw="soy-sauce"),
            _make("Mixed Spice Box 12 Compartments", 8, 15, 399, 699, 42.9, tags=["spices","kitchen"], sale=True, img_kw="spice-box"),
            _make("Turmeric Powder 500g Pure", 8, 15, 149, 199, 25.1, tags=["spices","turmeric"], sale=True, img_kw="turmeric-powder"),
            _make("Red Chilli Powder 500g", 8, 15, 129, 179, 27.9, tags=["spices","chilli"], sale=True, img_kw="chilli-powder"),
            _make("Garam Masala 200g", 8, 15, 99, 149, 33.6, tags=["spices","masala"], sale=True, img_kw="garam-masala"),
            _make("Peanut Butter Crunchy 1kg", 8, 15, 399, 599, 33.4, tags=["spread","protein"], sale=True, img_kw="peanut-butter"),
            _make("Honey Organic 500g", 8, 15, 349, 499, 30.1, tags=["honey","natural"], sale=True, img_kw="organic-honey"),
            _make("Mixed Dry Fruits 500g Premium", 8, 15, 499, 799, 37.5, tags=["dry-fruits","premium"], sale=True, feat=True, img_kw="dry-fruits-mix"),
            _make("Almonds California 250g", 8, 15, 349, 499, 30.1, tags=["dry-fruits","almonds"], sale=True, img_kw="california-almonds"),
            _make("Cashew Nuts Whole 250g", 8, 15, 299, 449, 33.4, tags=["dry-fruits","cashew"], sale=True, img_kw="cashew-nuts"),
            _make("Dark Chocolate 70% Cocoa 100g", 8, 15, 199, 299, 33.4, tags=["chocolate","premium"], sale=True, img_kw="dark-chocolate"),
            _make("Oreo Cookies Family Pack 300g", 8, 15, 99, 149, 33.6, tags=["cookies","snacks"], sale=True, img_kw="oreo-cookies"),
            _make("Chips Variety Pack 12 Pcs", 8, 15, 199, 299, 33.4, tags=["chips","snacks"], sale=True, img_kw="chips-variety"),
            _make("Muesli Fruit & Nut 1kg", 8, 15, 399, 599, 33.4, tags=["breakfast","healthy"], sale=True, img_kw="muesli-mix"),
            _make("Oats Quick Cook 1kg", 8, 15, 199, 299, 33.4, tags=["breakfast","oats"], sale=True, img_kw="quick-oats"),
            _make("Cornflakes Original 875g", 8, 15, 299, 399, 25.1, tags=["breakfast","cereal"], sale=True, img_kw="cornflakes"),
            _make("Orange Juice 1L Tropicana", 8, 15, 99, 149, 33.6, tags=["juice","beverages"], sale=True, img_kw="orange-juice"),
            _make("Coconut Water Pack of 6", 8, 15, 180, 240, 25.0, tags=["beverages","healthy"], sale=True, img_kw="coconut-water"),
            _make("Cola Soft Drink 2L", 8, 15, 79, 99, 20.2, tags=["soft-drink","beverages"], sale=True, img_kw="cola-drink"),
            _make("Energy Drink Pack of 4", 8, 15, 399, 499, 20.0, tags=["energy","beverages"], sale=True, img_kw="energy-drink"),
            _make("Mineral Water 1L Pack of 12", 8, 15, 180, tags=["water","beverages"], img_kw="mineral-water"),
            _make("Dishwash Liquid 1L", 8, 15, 149, 199, 25.1, tags=["cleaning","kitchen"], sale=True, img_kw="dishwash-liquid"),
            _make("Laundry Detergent Liquid 2L", 8, 15, 399, 549, 27.3, tags=["cleaning","laundry"], sale=True, img_kw="detergent-liquid"),
            _make("Floor Cleaner Disinfectant 1L", 8, 15, 149, 199, 25.1, tags=["cleaning","floor"], sale=True, img_kw="floor-cleaner"),
            _make("Toilet Cleaner 500ml Pack of 2", 8, 15, 129, 179, 27.9, tags=["cleaning","bathroom"], sale=True, img_kw="toilet-cleaner"),
            _make("Hand Wash Liquid 250ml Pack of 3", 8, 15, 149, 249, 40.2, tags=["hygiene","handwash"], sale=True, img_kw="hand-wash"),
            _make("Paper Towels Roll Pack of 6", 8, 15, 249, 349, 28.7, tags=["household","paper"], sale=True, img_kw="paper-towels"),
            _make("Garbage Bags Large 30 Pcs", 8, 15, 99, 149, 33.6, tags=["household","bags"], sale=True, img_kw="garbage-bags"),
            _make("Aluminium Foil 9m Roll", 8, 15, 79, 129, 38.8, tags=["kitchen","wrapping"], sale=True, img_kw="foil-roll"),
            _make("Cling Wrap 100m Roll", 8, 15, 129, 199, 35.2, tags=["kitchen","wrapping"], sale=True, img_kw="cling-wrap"),
            _make("Baby Diapers Pack of 40 Medium", 8, 15, 699, 999, 30.0, tags=["baby","diapers"], sale=True, img_kw="baby-diapers"),
        ]
        products.extend(groc)

        db.add_all(products)

        # ===== DEMO USER =====
        demo_user = User(
            email="demo@example.com",
            username="demo_user",
            hashed_password=get_password_hash("demo123"),
            full_name="Demo User",
        )
        db.add(demo_user)

        await db.commit()
        print("Database seeded successfully!")
        print(f"   - {len(cats)} categories")
        print(f"   - {len(brands)} brands")
        print(f"   - {len(products)} products")
        print(f"   - 1 demo user (demo@example.com / demo123)")


if __name__ == "__main__":
    asyncio.run(seed())
